baseurl = "http://docker-saigon.github.io"
languageCode = "en-us"
title = "Docker Saigon"
theme = "startbootstrap-clean-blog"
publishdir = "public"
canonifyurls = true
paginate = 10
copyright = "Code released under the Apache 2.0 license."
[author]
  name = "Docker Saigon"
[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "Blog for Dockers in Saigon"
  Author = "Docker Saigon"
  email = "docker-saigon@gmail.com"
  Ganalytics = "UA-69412248-1"
[[params.social]]
  title = "twitter"
  url = "https://twitter.com/docker_saigon"
[[params.social]]
  title = "github"
  url = "https://github.com/docker-saigon"
[[params.social]]
  title = "facebook"
  url = "https://www.facebook.com/DockerSaigon"

[[menu.main]]
  name = "home"
  url = "/"
  weight = -200

[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -180